version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python bot.py"
    env_file: .env
    tty: true
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mongo:latest
    logging:
      driver: none
    ports:
      - 27017:27017
    volumes:
      - ./tmp/mongodb_data:/data/db
